In [1]:
import os
import numpy as np
import random
import csv
from additional_functions import process_all

In [ ]:
import csv
import numpy as np
import matplotlib.pyplot as plt
from dataset import dataset

# All files were developed collaboratively

def process_all(user: str, shuffle_split: bool):
    
    # instantiates the datasets
    abalone_data = dataset('/home/'+user+'/CSCI_447/Project_3/Datasets/abalone.data', False)
    cancer_data = dataset('/home/'+user+'/CSCI_447/Project_3/Datasets/breast-cancer-wisconsin.data', False)
    fire_data = dataset('/home/'+user+'/CSCI_447/Project_3/Datasets/forestfires.data', False)
    glass_data = dataset('/home/'+user+'/CSCI_447/Project_3/Datasets/glass.data', False)
    machine_data = dataset('/home/'+user+'/CSCI_447/Project_3/Datasets/machine.data', False)
    soybean_data = dataset('/home/'+user+'/CSCI_447/Project_3/Datasets/soybean-small.data', False)
    
    
    # abalone processing
    abalone_data.oh_encode()
    abalone_data.normalize("regression")
    abalone_data.shuffle()
    abalone_data.sort('regression')
    abalone_data.split()
    abalone_data.fold()

    # cancer processing
    cancer_data.oh_encode()
    cancer_data.normalize("classification")
    cancer_data.remove_attribute()
    cancer_data.impute()
    cancer_data.shuffle()
    cancer_data.sort('classification')
    cancer_data.split()
    cancer_data.fold()

    # fire processing
    fire_data.oh_encode()
    fire_data.normalize("regression")
    fire_data.shuffle()
    fire_data.sort('regression')
    fire_data.split()
    fire_data.fold()

    # glass processing
    glass_data.oh_encode()
    glass_data.remove_attribute()
    glass_data.normalize("classification")
    glass_data.shuffle()
    glass_data.sort('classification')
    glass_data.split()
    glass_data.fold()

    # machine processing
    machine_data.oh_encode()
    machine_data.normalize("regression")
    machine_data.shuffle()
    machine_data.sort('regression')
    machine_data.split()
    machine_data.fold()
    
    # soybean processing
    soybean_data.oh_encode()
    soybean_data.normalize("classification")
    soybean_data.shuffle()
    soybean_data.sort('classification')
    soybean_data.split()
    soybean_data.fold()

    # Final shuffle of the data
    if (shuffle_split == True) :
        abalone_data.shuffle_splits()
        cancer_data.shuffle_splits()
        fire_data.shuffle_splits()
        glass_data.shuffle_splits()
        machine_data.shuffle_splits()
        soybean_data.shuffle_splits()

    # save the datasets
    abalone_data.save('abalone')
    cancer_data.save('cancer')
    fire_data.save('fire')
    glass_data.save('glass')
    machine_data.save('machine')
    soybean_data.save('soybean')

    return abalone_data, cancer_data, fire_data, glass_data, machine_data, soybean_data

In [3]:
abalone_data, cancer_data, fire_data, glass_data, machine_data, soybean_data = process_all('m28r778', False)

In [4]:
print(abalone_data.tune_set)


[[1.         0.         0.         ... 0.         0.         0.        ]
 [1.         0.18918919 0.15966387 ... 0.01119157 0.01096163 0.07142857]
 [1.         0.27027027 0.24369748 ... 0.02699144 0.02441455 0.10714286]
 ...
 [0.5        0.65540541 0.67226891 ... 0.16919026 0.37219731 0.71428571]
 [0.         0.78378378 0.81512605 ... 0.42988808 0.58146487 0.75      ]
 [0.5        0.84459459 0.81512605 ... 0.41079658 0.7060289  0.82142857]]


In [5]:
print(fire_data.tune_set)

[[3.75000000e-01 2.85714286e-01 0.00000000e+00 1.66666667e-01
  8.95483871e-01 8.47691247e-02 7.00129002e-02 6.77361854e-02
  3.82636656e-01 3.29411765e-01 2.55555556e-01 0.00000000e+00
  0.00000000e+00]
 [2.50000000e-01 2.85714286e-01 3.33333333e-01 1.00000000e+00
  9.40645161e-01 8.52170917e-01 8.74750792e-01 1.12299465e-01
  4.69453376e-01 4.82352941e-01 3.00000000e-01 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.44444444e-01 1.00000000e+00
  9.57419355e-01 4.68297726e-01 8.19162660e-01 1.63992870e-01
  6.20578778e-01 0.00000000e+00 5.55555556e-02 0.00000000e+00
  0.00000000e+00]
 [6.25000000e-01 4.28571429e-01 3.33333333e-01 0.00000000e+00
  5.78064516e-01 2.40179187e-01 7.70962824e-01 1.42602496e-02
  4.75884244e-01 6.70588235e-01 7.00000000e-01 0.00000000e+00
  0.00000000e+00]
 [3.75000000e-01 4.28571429e-01 3.33333333e-01 3.33333333e-01
  9.22580645e-01 3.39421089e-01 7.30972206e-01 1.12299465e-01
  6.17363344e-01 2.11764706e-01 3.00000000e-01 0.00000000e+0

In [6]:
print(machine_data.tune_set)

[[8.69565217e-02 6.14203219e-01 2.24544842e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.92307692e-02 2.27272727e-02
  3.49650350e-03 0.00000000e+00]
 [3.47826087e-01 8.84629561e-03 7.28253540e-02 1.40280561e-02
  1.46396396e-02 0.00000000e+00 1.53846154e-01 1.13636364e-01
  2.62237762e-02 3.27064595e-03]
 [3.76811594e-01 9.70635213e-03 5.93391773e-02 6.01202405e-03
  3.02802803e-02 0.00000000e+00 5.76923077e-02 5.68181818e-02
  1.74825175e-02 4.08830744e-03]
 [4.15458937e-01 1.21636565e-02 1.90829400e-01 2.20440882e-02
  4.59209209e-02 0.00000000e+00 1.15384615e-01 1.36363636e-01
  2.62237762e-02 6.54129191e-03]
 [8.40579710e-01 2.15014129e-02 1.23398517e-01 2.93086172e-02
  6.15615616e-02 0.00000000e+00 1.92307692e-02 2.27272727e-02
  2.09790210e-02 8.17661488e-03]
 [1.35265700e-01 3.44022607e-03 2.04315577e-01 2.00400802e-03
  9.28428428e-02 0.00000000e+00 1.92307692e-02 6.81818182e-02
  1.48601399e-02 1.06295993e-02]
 [4.20289855e-01 1.14264652e-02 8.29399865e-02 6.06212425e

In [7]:
print(cancer_data.tune_set)

[[0.         0.         0.         0.         0.11111111 0.1
  0.         0.         0.         0.        ]
 [0.55555556 0.         0.22222222 0.11111111 0.11111111 0.1
  0.         0.         0.         0.        ]
 [0.33333333 0.11111111 0.         0.         0.11111111 0.1
  0.11111111 0.         0.         0.        ]
 [0.         0.         0.         0.         0.11111111 0.1
  0.         0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.11111111 0.1
  0.11111111 0.         0.         0.        ]
 [0.         0.         0.         0.         0.11111111 0.1
  0.22222222 0.         0.         0.        ]
 [0.11111111 0.         0.         0.         0.22222222 0.1
  0.11111111 0.         0.         0.        ]
 [0.22222222 0.         0.         0.         0.11111111 0.1
  0.         0.         0.         0.        ]
 [0.44444444 0.         0.         0.         0.11111111 0.2
  0.11111111 0.         0.         0.        ]
 [0.22222222 0.         0.  

In [8]:
print(glass_data.tune_set)

[[0.26558385 0.39849624 0.77951002 0.26791277 0.54285714 0.0805153
  0.27881041 0.         0.         0.        ]
 [0.28007024 0.27669173 0.77282851 0.33956386 0.63928571 0.09661836
  0.28996283 0.         0.11764706 0.        ]
 [0.34855136 0.47518797 0.78619154 0.32087227 0.35714286 0.0821256
  0.31133829 0.03492063 0.         0.        ]
 [0.31123793 0.32180451 0.77505568 0.31152648 0.56071429 0.09661836
  0.27881041 0.         0.         0.        ]
 [0.28489903 0.33834586 0.78841871 0.28660436 0.56964286 0.10466989
  0.28810409 0.         0.         0.        ]
 [0.27524144 0.38195489 0.80623608 0.29595016 0.58392857 0.08856683
  0.24535316 0.         0.         0.        ]
 [0.28138718 0.36390977 0.80400891 0.23676012 0.6125     0.09178744
  0.26115242 0.         0.         0.        ]
 [0.30553117 0.39097744 0.85746102 0.29906542 0.53035714 0.08373591
  0.25       0.         0.         1.        ]
 [0.20851624 0.31428571 0.78396437 0.50155763 0.54464286 0.11111111
  0.23605948 0

In [9]:
print(soybean_data.tune_set)

[[1.         0.         1.         0.5        0.         0.33333333
  0.         0.         0.         1.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         1.         0.33333333 1.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [1.         0.         0.         1.         1.         0.
  0.66666667 0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         1.         0.         1.         0.         0.
  0.         1.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         1.        ]
 [0.         1.         1.         0.         0.         0.
  0.33333333 0.         1.         1.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.33333333 0.33333333 0.         1.
  0.         0