In [180]:
import os
import numpy as np
import random
import csv
from additional_functions import process_all

In [181]:
import csv
import numpy as np
import matplotlib.pyplot as plt
from dataset import dataset

# All files were developed collaboratively

def process_all(user: str, shuffle_split: bool):
    # instantiates the datasets
    abalone_data = dataset('/home/'+user+'/CSCI_447/Project_2/Datasets/abalone.data', False)
    cancer_data = dataset('/home/'+user+'/CSCI_447/Project_2/Datasets/breast-cancer-wisconsin.data', False)
    fire_data = dataset('/home/'+user+'/CSCI_447/Project_2/Datasets/forestfires.data', False)
    glass_data = dataset('/home/'+user+'/CSCI_447/Project_2/Datasets/glass.data', False)
    machine_data = dataset('/home/'+user+'/CSCI_447/Project_2/Datasets/machine.data', False)
    soybean_data = dataset('/home/'+user+'/CSCI_447/Project_2/Datasets/soybean-small.data', False)

    # abalone processing
    abalone_data.oh_encode()
    abalone_data.normalize("regression")
    abalone_data.shuffle()
    abalone_data.sort('regression')
    abalone_data.split()
    abalone_data.fold()

    # cancer processing
    cancer_data.oh_encode()
    cancer_data.normalize("classification")
    cancer_data.remove_attribute()
    cancer_data.impute()
    cancer_data.shuffle()
    cancer_data.sort('classification')
    cancer_data.split()
    cancer_data.fold()

    # fire processing
    fire_data.oh_encode()
    fire_data.normalize("regression")
    fire_data.shuffle()
    fire_data.sort('regression')
    fire_data.split()
    fire_data.fold()

    # glass processing
    glass_data.oh_encode()
    glass_data.remove_attribute()
    glass_data.normalize("classification")
    glass_data.shuffle()
    glass_data.sort('classification')
    glass_data.split()
    glass_data.fold()

    # machine processing
    machine_data.oh_encode()
    machine_data.normalize("regression")
    machine_data.shuffle()
    machine_data.sort('regression')
    machine_data.split()
    machine_data.fold()

    # soybean processing
    soybean_data.oh_encode()
    soybean_data.normalize("classification")
    #soybean_data.shuffle()
    soybean_data.sort('classification')
    soybean_data.split()
    soybean_data.fold()

    # Final shuffle of the data
    if (shuffle_split == True) :
        abalone_data.shuffle_splits()
        cancer_data.shuffle_splits()
        fire_data.shuffle_splits()
        glass_data.shuffle_splits()
        machine_data.shuffle_splits()
        soybean_data.shuffle_splits()

    # save the datasets
    abalone_data.save('abalone')
    cancer_data.save('cancer')
    fire_data.save('fire')
    glass_data.save('glass')
    machine_data.save('machine')
    soybean_data.save('soybean')

    return abalone_data, cancer_data, fire_data, glass_data, machine_data, soybean_data

In [182]:
abalone_data, cancer_data, fire_data, glass_data, machine_data, soybean_data = process_all('carlthedog3', True)

In [183]:
print(abalone_data.tune_set)


[[1.         0.52702703 0.53781513 ... 0.1560237  0.13801694 0.28571429]
 [0.         0.59459459 0.57142857 ... 0.32784727 0.24962631 0.25      ]
 [0.         0.24324324 0.23529412 ... 0.02304147 0.02541106 0.25      ]
 ...
 [0.5        0.63513514 0.62184874 ... 0.1961817  0.25759841 0.53571429]
 [0.         0.66891892 0.64705882 ... 0.29098091 0.2326856  0.25      ]
 [0.5        0.71621622 0.73109244 ... 0.3475971  0.29247633 0.28571429]]


In [184]:
print(fire_data.tune_set)

[[8.88888889e-01 5.00000000e-01 6.55172414e-01 6.52173913e-01
  9.29501085e-01 3.06340455e-01 8.17224432e-01 8.55614973e-02
  5.01607717e-01 6.37362637e-01 1.87500000e-01 0.00000000e+00
  1.84261670e-03]
 [7.77777778e-01 3.75000000e-01 4.48275862e-01 7.39130435e-01
  9.51193059e-01 1.63335631e-01 8.07512286e-01 1.97860963e-01
  4.69453376e-01 3.95604396e-01 4.27083333e-01 0.00000000e+00
  6.26122988e-03]
 [7.77777778e-01 3.75000000e-01 5.86206897e-01 6.08695652e-01
  9.34924078e-01 3.78359752e-01 6.21811374e-01 1.10516934e-01
  5.56270096e-01 3.73626374e-01 5.62500000e-01 0.00000000e+00
  0.00000000e+00]
 [5.55555556e-01 3.75000000e-01 6.55172414e-01 4.78260870e-01
  9.55531453e-01 3.37353549e-01 8.65083080e-01 1.71122995e-01
  2.54019293e-01 7.25274725e-01 3.33333333e-01 0.00000000e+00
  3.40104873e-03]
 [7.77777778e-01 5.00000000e-01 6.55172414e-01 6.08695652e-01
  9.59869848e-01 2.99448656e-01 8.10437632e-01 1.26559715e-01
  5.01607717e-01 4.61538462e-01 7.08333333e-01 0.00000000e+0

In [185]:
print(machine_data.tune_set)

[[4.20289855e-01 1.20407913e-02 8.29399865e-02 6.06212425e-02
  4.99499499e-01 1.25000000e-01 1.92307692e-02 3.06818182e-01
  1.59965035e-01 1.35731807e-01]
 [6.76328502e-01 1.87983782e-02 1.55091032e-02 2.48496994e-01
  4.99499499e-01 2.50000000e-01 1.53846154e-01 1.36363636e-01
  2.36888112e-01 2.05233034e-01]
 [6.28019324e-01 5.46013024e-01 2.22521915e-02 6.06212425e-02
  1.24124124e-01 3.12500000e-02 1.92307692e-02 3.40909091e-02
  4.37062937e-02 2.37121832e-02]
 [9.17874396e-02 3.07163042e-03 8.49629130e-02 7.00150301e-02
  9.59709710e-02 0.00000000e+00 1.15384615e-01 3.63636364e-01
  4.80769231e-02 2.04415372e-02]
 [4.87922705e-01 1.44980956e-02 1.40256237e-01 6.06212425e-02
  6.15615616e-02 3.12500000e-02 5.76923077e-02 3.40909091e-02
  2.44755245e-02 1.30825838e-02]
 [2.80193237e-01 7.24904779e-03 4.60552933e-01 6.01202405e-03
  3.02802803e-02 0.00000000e+00 1.92307692e-02 5.68181818e-03
  1.57342657e-02 3.27064595e-03]
 [3.18840580e-01 8.35483475e-03 5.27983817e-01 6.01202405e

In [186]:
print(cancer_data.tune_set)

[[0.         0.         0.         0.         0.         0.1
  0.11111111 0.         0.         0.        ]
 [0.77777778 1.         1.         1.         0.66666667 0.5
  0.33333333 0.77777778 0.66666667 1.        ]
 [0.55555556 1.         1.         0.11111111 0.77777778 1.
  0.66666667 0.22222222 0.22222222 1.        ]
 [0.22222222 0.66666667 0.66666667 0.33333333 0.33333333 0.9
  0.33333333 0.77777778 0.         1.        ]
 [0.         0.         0.         0.         0.11111111 0.1
  0.11111111 0.         0.         0.        ]
 [0.88888889 1.         1.         1.         1.         1.
  1.         1.         0.         1.        ]
 [0.         0.         0.         0.         0.11111111 0.1
  0.11111111 0.         0.11111111 0.        ]
 [0.33333333 0.         0.         0.         0.         0.1
  0.11111111 0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.11111111 0.1
  0.         0.         0.         0.        ]
 [0.88888889 0.44444444 0.4444

In [187]:
print(glass_data.tune_set)

[[0.52019315 0.38796992 0.79732739 0.16510903 0.38928571 0.01932367
  0.44052045 0.         0.05882353 0.        ]
 [0.48639157 0.37293233 0.83964365 0.15576324 0.38928571 0.02093398
  0.42657993 0.         0.         0.        ]
 [0.22036874 0.63458647 0.         0.61682243 0.62321429 0.
  0.30483271 0.21269841 0.         5.        ]
 [0.32309043 0.37142857 0.80846325 0.24299065 0.53928571 0.09178744
  0.27695167 0.02857143 0.33333333 1.        ]
 [0.26075505 0.34135338 0.77282851 0.46728972 0.51964286 0.10628019
  0.25557621 0.         0.         1.        ]
 [0.23309921 0.34736842 0.75723831 0.30218069 0.57142857 0.08373591
  0.29275093 0.         0.         2.        ]
 [0.04389816 0.33984962 0.77282851 0.25856698 0.56607143 0.09983897
  0.27137546 0.         0.60784314 0.        ]
 [0.32704126 0.39548872 0.76391982 0.35514019 0.4375     0.0821256
  0.29460967 0.         0.         1.        ]
 [0.46619842 0.45413534 0.22494432 0.33333333 0.425      0.0531401
  0.53066914 0.       

In [188]:
print(soybean_data.tune_set)

[[0.         1.         1.         0.         0.         0.33333333
  0.33333333 0.         1.         0.5               nan 0.
         nan        nan        nan        nan        nan        nan
         nan 0.         0.33333333 0.33333333 0.         1.
  1.         0.         0.         1.                nan        nan
         nan        nan        nan        nan 0.         2.        ]
 [0.         1.         1.         0.5        1.         0.33333333
  0.33333333 0.         0.         0.                nan 1.
         nan        nan        nan        nan        nan        nan
         nan 0.         0.33333333 0.66666667 0.         1.
  0.         0.         0.         1.                nan        nan
         nan        nan        nan        nan 1.         3.        ]
 [1.         0.         0.         1.         1.         0.
  0.66666667 0.         0.         0.                nan 1.
         nan        nan        nan        nan        nan        nan
         nan 1.         0.